admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

base:
    resource: "@BaseBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

discutea_forum:
    resource: "@DForumBundle/Resources/config/routing.yml"
    prefix:   /

