<?php

namespace BaseBundle\Repository;

/**
 * FavoriRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class FavoriRepository extends \Doctrine\ORM\EntityRepository {
    public function findFav($idF)
    {

        $Query=$this->getEntityManager()
            ->createQuery("
        select p  from BaseBundle:Favori p where p.user =:idF ")
//            ->createQuery(" select v from ClientBundle:Participation v where v.idevent like :idevent  ")
            ->setParameter('idF',$idF);


        return $Query->getResult();

    }


}
